/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tpc_spark_arrow_fletcher_FletcherProcessor_BufferDescriptor__ */

#ifndef _Included_tpc_spark_arrow_fletcher_FletcherProcessor_BufferDescriptor__
#define _Included_tpc_spark_arrow_fletcher_FletcherProcessor_BufferDescriptor__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
