/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tpc_spark_arrow_fletcher_PlatformWrapper */

#ifndef _Included_tpc_spark_arrow_fletcher_PlatformWrapper
#define _Included_tpc_spark_arrow_fletcher_PlatformWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tpc_spark_arrow_fletcher_PlatformWrapper
 * Method:    initPlatformWrapper
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_tpc_spark_arrow_fletcher_PlatformWrapper_initPlatformWrapper
  (JNIEnv *, jobject, jlong);

/*
 * Class:     tpc_spark_arrow_fletcher_PlatformWrapper
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tpc_spark_arrow_fletcher_PlatformWrapper_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
